### ISSUE TITLE
ADR 리뷰

### ISSUE THREAD

**Issue by KENNYSOFT** [2021-WISET-jobsearching-mentoring-GCDAC/tagged-address#3]
### Monorepo

네 2종류 정도면 큰 무리 없겠고 branching 전략만 잘 정리 해 주세요.

### Application

모바일 기기에 실제 저장되어 있는 주소록에 바로 연동되면 좋겠어서 애플리케이션만이 가능해 보입니다.

#### Android

두 분 모두 사용하시는 기기와 같은 플랫폼인가요?

최소 SDK 버전은 몇으로 생각하시나요?

데이터 저장은 어떻게 할지도 고려해주세요. (ex. SharedPreference, SQLite, Realm)

#### Java

Kotlin이 나온지 얼마 되지 않아 레퍼런스가 부족할 수 있는 점 이해합니다. Android target SDK version에 따라 사용할 수 있는 Java 언어의 버전도 달라질텐데, 이 부분만 확인 해주세요.

### Backend

아래 사항에 앞서, 백엔드 구축의 목적이 무엇인가요? 동기화? 데이터 수집?

#### Spring Boot

네 경험 있는 것 사용하는 것도 좋습니다. 버전(ex. 2.5.x)과 Spring Cloud 같은 추가 프로젝트 사용 여부도 언급되면 좋겠습니다.

빌드 시스템으로 Maven을 쓸지 Gradle을 쓸지도 적어주시고, DB 연동이 필요한지 확인해주세요.

#### Java

언어 버전도 지정해주세요. 8, 11, 16 등의 선택지가 있고 개인적인 추천은 11 입니다.

#### AWS

12개월동안 모든 서비스를 사용해볼 수 있는가 했을 때 그건 아니었던 것으로 기억합니다. 이를테면 Docker container로 만들어서 ECS를 돌리거나, Kubernetes를 사용하겠다 해서 EKS를 돌리거나, 도메인 연결을 하겠다 해서 Route53 같은건 다 free tier에 안 들어가는 것으로 기억하는데요, EC2는 잘 사용해볼 수 있겠지만 그렇다고 'AWS 사용 경험' 또는 'AWS 공부를 했음' 이라고 하기에는 좀 애매합니다. 그 연결된 ecosystem을 잘 활용한 것까지는 아니라서요.

Cloud instance가 필요한 것이라면 GCP와 OCI에서는 평생 무료 vm을 제공하기도 합니다. 사실 뭐 성능은 비슷비슷 할거라 선호하는 곳 잘 선택해주세요.

**Comment by jiwoo-kimm** [comment]
리뷰 감사합니다! 말씀해주신 내용을 바탕으로 ADR을 업데이트했으니 확인 부탁드립니다.
그리고 ADR에 직접 적진 않았지만, 말씀드리거나 여쭤보고 싶은 내용이 있어서 추가로 코멘트를 남깁니다.

- 프로젝트 본격적으로 진행하면서 branching 전략을 포함한 규칙을 세울 계획입니다.
- 한 명은 아이폰이지만, 안드로이드 에뮬레이터로 테스트하며 개발할 계획입니다.
- AWS가 가장 레퍼런스가 많기도 하고, 추가로 사용하고 싶은 기능이 생기면 쉽게 확장할 수 있을 것 같아서 AWS로 선택했습니다.
- 멘토님께서 Java 11을 추천해주시는 이유가 있으신가요? Spring Boot 2.5는 Java 16도 지원하는데, 최신 버전이 아닌 11을 선택해야 하는 이유가 궁금합니다.

**Comment by KENNYSOFT** [comment]
네 잘 확인했습니다.

AWS로 할 수 있는 다양한 것들을 경험해 보면 정말 재밌고 신기한 것들도 많아서, 어디선가 크레딧 지원을 받거나, 아니면 약간의 비용을 투자해서라도 써보면 큰 도움이 될 것입니다.

이를테면 도메인을 구입하여 CloudFront 배포, ACM으로 Route53 통한 인증서 발급, 스팟 인스턴스 사용을 통한 저렴한 EKS 등...

Java 11은 LTS라서 그런데요, Java 16은 OpenJDK를 사용한다면 6개월 후 업그레이드가 끝나기에 바로 17로 넘어가야 합니다. 요즘은 docker로 돌리니 base image만 교체하면 되어서 jdk 선택에 따른 부담은 많이 떨어지기는 했지만, Spring Boot 2.6이나 Gradle 등 ecosystem이 바로 따라올지 확신하기가 어렵습니다. (그나마 희망적인 소식은 17은 LTS 예정입니다.)

Azul 같은 경우 중간중간에 MTS를 두기도 합니다. 참고: https://www.azul.com/products/azul-support-roadmap/
